package team.a9043.sis_message_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.sis_message_system.entity.SisCourse;
import team.a9043.sis_message_system.entity.SisCourseExample;

public interface SisCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    long countByExample(SisCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int deleteByExample(SisCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int deleteByPrimaryKey(String scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int insert(SisCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int insertSelective(SisCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    List<SisCourse> selectByExample(SisCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    SisCourse selectByPrimaryKey(String scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisCourse record, @Param("example") SisCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByExample(@Param("record") SisCourse record, @Param("example") SisCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByPrimaryKeySelective(SisCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByPrimaryKey(SisCourse record);
}