package team.a9043.sis_message_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.sis_message_system.entity.SisJoinCourse;
import team.a9043.sis_message_system.entity.SisJoinCourseExample;

public interface SisJoinCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    long countByExample(SisJoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int deleteByExample(SisJoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int deleteByPrimaryKey(Integer sjcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int insert(SisJoinCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int insertSelective(SisJoinCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    List<SisJoinCourse> selectByExample(SisJoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    SisJoinCourse selectByPrimaryKey(Integer sjcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisJoinCourse record, @Param("example") SisJoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByExample(@Param("record") SisJoinCourse record, @Param("example") SisJoinCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByPrimaryKeySelective(SisJoinCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByPrimaryKey(SisJoinCourse record);
}