package team.a9043.sis_message_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.sis_message_system.entity.SisSchedule;
import team.a9043.sis_message_system.entity.SisScheduleExample;

public interface SisScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    long countByExample(SisScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int deleteByExample(SisScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int deleteByPrimaryKey(Integer ssId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int insert(SisSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int insertSelective(SisSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    List<SisSchedule> selectByExample(SisScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    SisSchedule selectByPrimaryKey(Integer ssId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisSchedule record, @Param("example") SisScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByExample(@Param("record") SisSchedule record, @Param("example") SisScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByPrimaryKeySelective(SisSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByPrimaryKey(SisSchedule record);
}