package team.a9043.sis_message_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.sis_message_system.entity.SisUser;
import team.a9043.sis_message_system.entity.SisUserExample;

public interface SisUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    long countByExample(SisUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int deleteByExample(SisUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int deleteByPrimaryKey(String suId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int insert(SisUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int insertSelective(SisUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    List<SisUser> selectByExample(SisUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    SisUser selectByPrimaryKey(String suId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") SisUser record, @Param("example") SisUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByExample(@Param("record") SisUser record, @Param("example") SisUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByPrimaryKeySelective(SisUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    int updateByPrimaryKey(SisUser record);
}