package team.a9043.sis_message_system.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class SisCourse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_course.sc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_course.sc_act_size
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer scActSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_course.sc_att_rate
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private BigDecimal scAttRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_course.sc_grade
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer scGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_course.sc_max_size
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer scMaxSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_course.sc_name
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String scName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_course.sc_need_monitor
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Boolean scNeedMonitor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_course.su_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String suId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_course.sc_id
     *
     * @return the value of sis_course.sc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_course.sc_id
     *
     * @param scId the value for sis_course.sc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setScId(String scId) {
        this.scId = scId == null ? null : scId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_course.sc_act_size
     *
     * @return the value of sis_course.sc_act_size
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getScActSize() {
        return scActSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_course.sc_act_size
     *
     * @param scActSize the value for sis_course.sc_act_size
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setScActSize(Integer scActSize) {
        this.scActSize = scActSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_course.sc_att_rate
     *
     * @return the value of sis_course.sc_att_rate
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public BigDecimal getScAttRate() {
        return scAttRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_course.sc_att_rate
     *
     * @param scAttRate the value for sis_course.sc_att_rate
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setScAttRate(BigDecimal scAttRate) {
        this.scAttRate = scAttRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_course.sc_grade
     *
     * @return the value of sis_course.sc_grade
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getScGrade() {
        return scGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_course.sc_grade
     *
     * @param scGrade the value for sis_course.sc_grade
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setScGrade(Integer scGrade) {
        this.scGrade = scGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_course.sc_max_size
     *
     * @return the value of sis_course.sc_max_size
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getScMaxSize() {
        return scMaxSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_course.sc_max_size
     *
     * @param scMaxSize the value for sis_course.sc_max_size
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setScMaxSize(Integer scMaxSize) {
        this.scMaxSize = scMaxSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_course.sc_name
     *
     * @return the value of sis_course.sc_name
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getScName() {
        return scName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_course.sc_name
     *
     * @param scName the value for sis_course.sc_name
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setScName(String scName) {
        this.scName = scName == null ? null : scName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_course.sc_need_monitor
     *
     * @return the value of sis_course.sc_need_monitor
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Boolean getScNeedMonitor() {
        return scNeedMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_course.sc_need_monitor
     *
     * @param scNeedMonitor the value for sis_course.sc_need_monitor
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setScNeedMonitor(Boolean scNeedMonitor) {
        this.scNeedMonitor = scNeedMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_course.su_id
     *
     * @return the value of sis_course.su_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getSuId() {
        return suId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_course.su_id
     *
     * @param suId the value for sis_course.su_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSuId(String suId) {
        this.suId = suId == null ? null : suId.trim();
    }
}