package team.a9043.sis_message_system.entity;

import java.io.Serializable;

public class SisJoinCourse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_join_course.sjc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer sjcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_join_course.join_course_type
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer joinCourseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_join_course.sc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_join_course.su_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String suId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_join_course
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_join_course.sjc_id
     *
     * @return the value of sis_join_course.sjc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getSjcId() {
        return sjcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_join_course.sjc_id
     *
     * @param sjcId the value for sis_join_course.sjc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSjcId(Integer sjcId) {
        this.sjcId = sjcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_join_course.join_course_type
     *
     * @return the value of sis_join_course.join_course_type
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getJoinCourseType() {
        return joinCourseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_join_course.join_course_type
     *
     * @param joinCourseType the value for sis_join_course.join_course_type
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setJoinCourseType(Integer joinCourseType) {
        this.joinCourseType = joinCourseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_join_course.sc_id
     *
     * @return the value of sis_join_course.sc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_join_course.sc_id
     *
     * @param scId the value for sis_join_course.sc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setScId(String scId) {
        this.scId = scId == null ? null : scId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_join_course.su_id
     *
     * @return the value of sis_join_course.su_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getSuId() {
        return suId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_join_course.su_id
     *
     * @param suId the value for sis_join_course.su_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSuId(String suId) {
        this.suId = suId == null ? null : suId.trim();
    }
}