package team.a9043.sis_message_system.entity;

import java.io.Serializable;

public class SisSchedule implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.ss_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer ssId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.ss_day_of_week
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer ssDayOfWeek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.ss_end_time
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer ssEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.ss_end_week
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer ssEndWeek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.ss_fortnight
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer ssFortnight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.ss_start_time
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer ssStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.ss_start_week
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer ssStartWeek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.ss_year_et_term
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String ssYearEtTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.sc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String scId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.ss_suspension
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String ssSuspension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.ss_room
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String ssRoom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_schedule.sl_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private Integer slId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_schedule
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.ss_id
     *
     * @return the value of sis_schedule.ss_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getSsId() {
        return ssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.ss_id
     *
     * @param ssId the value for sis_schedule.ss_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSsId(Integer ssId) {
        this.ssId = ssId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.ss_day_of_week
     *
     * @return the value of sis_schedule.ss_day_of_week
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getSsDayOfWeek() {
        return ssDayOfWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.ss_day_of_week
     *
     * @param ssDayOfWeek the value for sis_schedule.ss_day_of_week
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSsDayOfWeek(Integer ssDayOfWeek) {
        this.ssDayOfWeek = ssDayOfWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.ss_end_time
     *
     * @return the value of sis_schedule.ss_end_time
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getSsEndTime() {
        return ssEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.ss_end_time
     *
     * @param ssEndTime the value for sis_schedule.ss_end_time
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSsEndTime(Integer ssEndTime) {
        this.ssEndTime = ssEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.ss_end_week
     *
     * @return the value of sis_schedule.ss_end_week
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getSsEndWeek() {
        return ssEndWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.ss_end_week
     *
     * @param ssEndWeek the value for sis_schedule.ss_end_week
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSsEndWeek(Integer ssEndWeek) {
        this.ssEndWeek = ssEndWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.ss_fortnight
     *
     * @return the value of sis_schedule.ss_fortnight
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getSsFortnight() {
        return ssFortnight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.ss_fortnight
     *
     * @param ssFortnight the value for sis_schedule.ss_fortnight
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSsFortnight(Integer ssFortnight) {
        this.ssFortnight = ssFortnight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.ss_start_time
     *
     * @return the value of sis_schedule.ss_start_time
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getSsStartTime() {
        return ssStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.ss_start_time
     *
     * @param ssStartTime the value for sis_schedule.ss_start_time
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSsStartTime(Integer ssStartTime) {
        this.ssStartTime = ssStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.ss_start_week
     *
     * @return the value of sis_schedule.ss_start_week
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getSsStartWeek() {
        return ssStartWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.ss_start_week
     *
     * @param ssStartWeek the value for sis_schedule.ss_start_week
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSsStartWeek(Integer ssStartWeek) {
        this.ssStartWeek = ssStartWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.ss_year_et_term
     *
     * @return the value of sis_schedule.ss_year_et_term
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getSsYearEtTerm() {
        return ssYearEtTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.ss_year_et_term
     *
     * @param ssYearEtTerm the value for sis_schedule.ss_year_et_term
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSsYearEtTerm(String ssYearEtTerm) {
        this.ssYearEtTerm = ssYearEtTerm == null ? null : ssYearEtTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.sc_id
     *
     * @return the value of sis_schedule.sc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.sc_id
     *
     * @param scId the value for sis_schedule.sc_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setScId(String scId) {
        this.scId = scId == null ? null : scId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.ss_suspension
     *
     * @return the value of sis_schedule.ss_suspension
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getSsSuspension() {
        return ssSuspension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.ss_suspension
     *
     * @param ssSuspension the value for sis_schedule.ss_suspension
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSsSuspension(String ssSuspension) {
        this.ssSuspension = ssSuspension == null ? null : ssSuspension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.ss_room
     *
     * @return the value of sis_schedule.ss_room
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getSsRoom() {
        return ssRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.ss_room
     *
     * @param ssRoom the value for sis_schedule.ss_room
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSsRoom(String ssRoom) {
        this.ssRoom = ssRoom == null ? null : ssRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_schedule.sl_id
     *
     * @return the value of sis_schedule.sl_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public Integer getSlId() {
        return slId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_schedule.sl_id
     *
     * @param slId the value for sis_schedule.sl_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSlId(Integer slId) {
        this.slId = slId;
    }
}