package team.a9043.sis_message_system.entity;

import java.io.Serializable;

public class SisUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_user.su_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String suId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_user.su_authorities_str
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String suAuthoritiesStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_user.su_name
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String suName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_user.su_openid
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String suOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sis_user.su_password
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private String suPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sis_user
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_user.su_id
     *
     * @return the value of sis_user.su_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getSuId() {
        return suId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_user.su_id
     *
     * @param suId the value for sis_user.su_id
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSuId(String suId) {
        this.suId = suId == null ? null : suId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_user.su_authorities_str
     *
     * @return the value of sis_user.su_authorities_str
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getSuAuthoritiesStr() {
        return suAuthoritiesStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_user.su_authorities_str
     *
     * @param suAuthoritiesStr the value for sis_user.su_authorities_str
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSuAuthoritiesStr(String suAuthoritiesStr) {
        this.suAuthoritiesStr = suAuthoritiesStr == null ? null : suAuthoritiesStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_user.su_name
     *
     * @return the value of sis_user.su_name
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getSuName() {
        return suName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_user.su_name
     *
     * @param suName the value for sis_user.su_name
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSuName(String suName) {
        this.suName = suName == null ? null : suName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_user.su_openid
     *
     * @return the value of sis_user.su_openid
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getSuOpenid() {
        return suOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_user.su_openid
     *
     * @param suOpenid the value for sis_user.su_openid
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSuOpenid(String suOpenid) {
        this.suOpenid = suOpenid == null ? null : suOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sis_user.su_password
     *
     * @return the value of sis_user.su_password
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public String getSuPassword() {
        return suPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sis_user.su_password
     *
     * @param suPassword the value for sis_user.su_password
     *
     * @mbg.generated Sun Oct 14 18:19:50 CST 2018
     */
    public void setSuPassword(String suPassword) {
        this.suPassword = suPassword == null ? null : suPassword.trim();
    }
}